### ISSUE TITLE
Поправить оформление

### ISSUE THREAD

**Issue by coursar** [maratkhambelov/purchaseCalculator#10]
https://github.com/maratkhambelov/purchaseCalculator/blob/cb23ea3249c6d0436482c58c5e4383619d128b35/src/js/lib.js#L27-L43

**Comment by maratkhambelov** [comment]
исправлено : 
https://github.com/maratkhambelov/purchaseCalculator/blob/60f4db709d06576f28817c70790d9895345c0e6a/src/js/lib.js#L27-L40
