### ISSUE TITLE
Расчётные значения лучше не кэшировать (не хранить), пока в этом не возникнет необходимости

### ISSUE THREAD

**Issue by coursar** [maratkhambelov/purchaseCalculator#11]
https://github.com/maratkhambelov/purchaseCalculator/blob/cb23ea3249c6d0436482c58c5e4383619d128b35/src/js/lib.js#L29

**Comment by maratkhambelov** [comment]
Исправлено, убрано из кэширования

**Comment by coursar** [comment]
Issue надо закрывать сообщениями коммитов
