### ISSUE TITLE
Поправить оформление кода

### ISSUE THREAD

**Issue by coursar** [maratkhambelov/purchaseCalculator#13]
https://github.com/maratkhambelov/purchaseCalculator/blob/cb23ea3249c6d0436482c58c5e4383619d128b35/src/js/storage.js#L41-L45

**Comment by maratkhambelov** [comment]
не понял что именно менять?
подскажите где искать документ, в котором описаны правила оформления кода

**Comment by coursar** [comment]
Ctrl + Alt + L в WebStorm
