### ISSUE TITLE
Обращение к первому элементу пустого массива

### ISSUE THREAD

**Issue by coursar** [maratkhambelov/purchaseCalculator#5]
https://github.com/maratkhambelov/purchaseCalculator/blob/7c18b411e5c1e9b4032c50e412844ab7f405c97d/src/js/lib.js#L32-L35

Если массив у вас пустой, что вы проверяете на 33 строке, то как тогда на 32 вы можете безопасно обращаться к первому элементу массива?

**Comment by maratkhambelov** [comment]
сделано https://github.com/maratkhambelov/purchaseCalculator/blob/138c2f21b2014d44b381d9a2ddb04158ce8daf9a/src/js/lib.js#L33-L46

**Comment by coursar** [comment]
не понял вашего ответа

**Comment by maratkhambelov** [comment]
Вы ранее говорили заменить такой for(let i = 1; i < this.items.length; i++)  на for ... of. я не сделал его. поэтому написал здесь об этом
