### ISSUE TITLE
Проверить ДЗ Lection 10

### ISSUE THREAD

**Issue by maratkhambelov** [maratkhambelov/purchaseCalculator#8]
Реализуйте в проекте со списком покупок:
1. Хранение списка в LocalStorage
2. Кнопку "удалить всё", которая стирает всё
из списка и из LocalStorage
_________________
Выполнено 
1. Выполнено
2. Выполнено
Дополнительная информация:
- АвтоТесты не написаны

**Comment by coursar** [comment]
Проверил
